### ISSUE TITLE
docker-lechacal-homeassistant  won't start.

### ISSUE THREAD

**Issue by cmora111** [ned-kelly/docker-lechacal-homeassistant#6]
SyntaxError: /opt/lechacal/config/device-mapping/RPICT8.json: Unexpected string in JSON at position 4699
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1171:22)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/opt/lechacal/server.js:19:30)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
error: Forever detected script exited with code: 1
error: Script restart attempt #9

**Comment by cmora111** [comment]
Nevermind. I found the problem, config missing a ",".
